### ISSUE TITLE
Collab

### ISSUE THREAD

**Issue by RevealedSoulEven** [JReverse/SnapDataFriendParser#2]
First of all sorry to create an issue, but I have no way to contact you. Please can I get your discord or telegram I want to continue SnapMod project which is already currently being updated by me(see my github). I need your help for the continuation of the project until rodit gives some updates.
My telegram username is in my github profile. Eager to get your response soon.
Thank you.

**Comment by JReverse** [comment]
@RevealedSoulEven leave your contact info. i don't publicly leave my contact for various reasons since i'm in the RE scene i get alot of spam. Once i contact you i will reply here to confirm its me.

**Comment by RevealedSoulEven** [comment]
Sure sir. My telegram is @soulevenofficial
And discord is "Revealed SoulEven#4238"

**Comment by RevealedSoulEven** [comment]
@JReverse

**Comment by JReverse** [comment]
Sent on Discord @RevealedSoulEven
